// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: modules/auth/authPb/authPb.proto

package authPb_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type AccessTokenSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenSearchReq) Reset() {
	*x = AccessTokenSearchReq{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchReq) ProtoMessage() {}

func (x *AccessTokenSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchReq.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenSearchReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessTokenSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenSearchRes) Reset() {
	*x = AccessTokenSearchRes{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchRes) ProtoMessage() {}

func (x *AccessTokenSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchRes.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenSearchRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_modules_auth_authPb_authPb_proto protoreflect.FileDescriptor

const file_modules_auth_authPb_authPb_proto_rawDesc = "" +
	"\n" +
	" modules/auth/authPb/authPb.proto\"8\n" +
	"\x14AccessTokenSearchReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"0\n" +
	"\x14AccessTokenSearchRes\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid2T\n" +
	"\x0fAuthGrpcService\x12A\n" +
	"\x11AccessTokenSearch\x12\x15.AccessTokenSearchReq\x1a\x15.AccessTokenSearchResB/Z-user-manages/modules/auth/authPb/authPb.protob\x06proto3"

var (
	file_modules_auth_authPb_authPb_proto_rawDescOnce sync.Once
	file_modules_auth_authPb_authPb_proto_rawDescData []byte
)

func file_modules_auth_authPb_authPb_proto_rawDescGZIP() []byte {
	file_modules_auth_authPb_authPb_proto_rawDescOnce.Do(func() {
		file_modules_auth_authPb_authPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)))
	})
	return file_modules_auth_authPb_authPb_proto_rawDescData
}

var file_modules_auth_authPb_authPb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_auth_authPb_authPb_proto_goTypes = []any{
	(*AccessTokenSearchReq)(nil), // 0: AccessTokenSearchReq
	(*AccessTokenSearchRes)(nil), // 1: AccessTokenSearchRes
}
var file_modules_auth_authPb_authPb_proto_depIdxs = []int32{
	0, // 0: AuthGrpcService.AccessTokenSearch:input_type -> AccessTokenSearchReq
	1, // 1: AuthGrpcService.AccessTokenSearch:output_type -> AccessTokenSearchRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authPb_authPb_proto_init() }
func file_modules_auth_authPb_authPb_proto_init() {
	if File_modules_auth_authPb_authPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authPb_authPb_proto_goTypes,
		DependencyIndexes: file_modules_auth_authPb_authPb_proto_depIdxs,
		MessageInfos:      file_modules_auth_authPb_authPb_proto_msgTypes,
	}.Build()
	File_modules_auth_authPb_authPb_proto = out.File
	file_modules_auth_authPb_authPb_proto_goTypes = nil
	file_modules_auth_authPb_authPb_proto_depIdxs = nil
}
